name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libclang-dev

      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run Rust tests
        run: cargo test --workspace
